name: Bridge Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      # - name: Copy files to io repository
      #   run: cp -R ./public/. ./Ucancel.GitHub.io/

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Commit and push changes
        env:
          remote-repo: ${{ secrets.REMOTE_REPO }}
        run: |
          cd ./Ucancel.GitHub.io
          git remote set-url origin "$remote-repo"
          git checkout main
          cp -R ../public/. .
          git add -A
          git commit -m "Update documentation"
          git push origin main