name: Bridge Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update

      # - name: Copy files to io repository
      #   run: cp -R ./public/. ./Ucancel.GitHub.io/

      - name: Commit and push changes
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VCANCEL_SSH_PRIVATE }}
        run: |
          cd ./Ucancel.GitHub.io
          git remote set-url origin git@github.com:Ucancel/Ucancel.GitHub.io.git
          git checkout main
          cp -R ../public/. .
          git add -A
          git commit -m "Update documentation"
          git push origin main